//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8762
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bdw.Application.Salt.Web.Administration.Unit {
    
    
    public partial class UnitDetails {
        
        /// <summary>
        /// pagTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pagTitle;
        
        /// <summary>
        /// ucStyle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Bdw.Application.Salt.Web.General.UserControls.Style ucStyle;
        
        /// <summary>
        /// Form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm Form1;
        
        /// <summary>
        /// ucHeader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Bdw.Application.Salt.Web.General.UserControls.Navigation.Header ucHeader;
        
        /// <summary>
        /// ucAdminMenu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Bdw.Application.Salt.Web.General.UserControls.Navigation.AdminMenu ucAdminMenu;
        
        /// <summary>
        /// lblUnitName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Localization.LocalizedLabel lblUnitName;
        
        /// <summary>
        /// lblUnitID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Localization.LocalizedLabel lblUnitID;
        
        /// <summary>
        /// lblStatus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Localization.LocalizedLabel lblStatus;
        
        /// <summary>
        /// lblPathwayLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Localization.LocalizedLabel lblPathwayLabel;
        
        /// <summary>
        /// lblSubUnits control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Localization.LocalizedLabel lblSubUnits;
        
        /// <summary>
        /// lblUsers control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Localization.LocalizedLabel lblUsers;
        
        /// <summary>
        /// litPage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Localization.LocalizedLiteral litPage;
        
        /// <summary>
        /// Localizedliteral1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Localization.LocalizedLiteral Localizedliteral1;
        
        /// <summary>
        /// litOf control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Localization.LocalizedLiteral litOf;
        
        /// <summary>
        /// litDisplayed control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Localization.LocalizedLiteral litDisplayed;
        
        /// <summary>
        /// lblLinks control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Localization.LocalizedLabel lblLinks;
        
        /// <summary>
        /// lnkAssign control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Localization.LocalizedLiteral lnkAssign;
        
        /// <summary>
        /// lnkSetRules control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Localization.LocalizedLiteral lnkSetRules;
        
        /// <summary>
        /// lnkManagaeUnitAdmin control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Localization.LocalizedLiteral lnkManagaeUnitAdmin;
        
        /// <summary>
        /// ucFooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Bdw.Application.Salt.Web.General.UserControls.Navigation.Footer ucFooter;
    }
}
