namespace Bdw.Application.Salt.Web.General.UserControls
{
	using System;
	using System.Data;
	using System.Drawing;
	using System.Web;
	using System.Web.UI.WebControls;
	using System.Web.UI.HtmlControls;
    using Bdw.Application.Salt.BusinessServices;

	/// <summary>
	/// If the Org is known then 
    ///     If the org has a customised CSS entry in tblClientConfig Then
    ///         Use the custom entry in tblClientConfig
    ///     Else
    ///         Use the default (null) entry in tblClientConfig
    ///     End if
	/// Else
	///     The css from tblAppConfig is used.
	/// End If
	/// </summary>
	public partial class Style : System.Web.UI.UserControl
	{
        /// <summary>
        /// Style sheet link
        /// </summary>
        protected System.Web.UI.HtmlControls.HtmlGenericControl lnkStyleSheet;

		/// <summary>
		/// Style sheet for printing.
		/// </summary>
		//protected System.Web.UI.HtmlControls.HtmlGenericControl lnkStyleSheetPrint;

		protected void Page_Load(object sender, System.EventArgs e)
		{
				string strCss="";

				// If the organisation is known
				try
                {
					OrganisationConfig objOrgConfig = new OrganisationConfig();
					strCss = objOrgConfig.GetOne(Utilities.UserContext.UserData.OrgID,"css");                

					// If its an empty string then use the application name
					if(strCss.Length == 0)
					{
					strCss = Utilities.ApplicationSettings.StyleSheet;
					}

					// append '.css' if requied
					if( !strCss.ToLower().EndsWith(".css") )
					{
					strCss += ".css";
					}

					strCss = "/general/css/" + strCss;

					// Update the stylesheet link
					lnkStyleSheet.Attributes.Add("href", strCss);
                }

				// If the organisation isnt known then default css is used.
				catch
				{
					// Update the stylesheet link
					strCss = Utilities.ApplicationSettings.StyleSheet;

					// append '.css' if requied
					if( !strCss.ToLower().EndsWith(".css") )
					{
						strCss += ".css";
					}
					strCss = "/general/css/" + strCss;
					lnkStyleSheet.Attributes.Add("href", strCss);
				}   

			// Style sheet link for printing
			//lnkStyleSheetPrint.Attributes.Add("href","/General/css/PrintFriendly.css");
			
		}

		#region Web Form Designer generated code

		/// <summary>
		/// Autogenerated event handler
		/// </summary>
		/// <param name="e"></param>
		override protected void OnInit(EventArgs e)
		{
			//
			// CODEGEN: This call is required by the ASP.NET Web Form Designer.
			//
			InitializeComponent();
			base.OnInit(e);
		}
		
		/// <summary>
		///		Required method for Designer support - do not modify
		///		the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
		}
		#endregion
	}
}
